sonar.projectKey=leoguimaraes49_projeto-integrador-chamados
sonar.organization=leoguimaraes49
sonar.projectName=Sistema de Gerenciamento de Chamados

sonar.sources=backend/src,frontend/src
sonar.tests=backend/tests
sonar.test.inclusions=backend/tests/**/*.test.js
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
sonar.coverage.exclusions=backend/src/app.js,backend/src/config/**,backend/src/db/**,backend/src/middleware/**,backend/src/repositories/**,backend/src/routes/**,backend/src/server.js,frontend/src/**
